export enum TagColor {
    White = 'White',
    Black = 'Black',
    Grey = 'Grey',
    Brown = 'Brown',
    Amber = 'amber',
    Blue = 'blue',
    Cyan = 'cyan',
    Emerald = 'emerald',
    Fuchsia = 'fuchsia',
    Green = 'green',
    Indigo = 'indigo',
    Lime = 'lime',
    Orange = 'orange',
    Pink = 'pink',
    Purple = 'purple',
    Red = 'red',
    Rose = 'rose',
    Sky = 'sky',
    Teal = 'teal',
    Violet = 'violet',
    Yellow = 'yellow',
}
